### ISSUE TITLE
ModuleNotFoundError: No module named 'warpctc'

### ISSUE THREAD

**Issue by mausamsion** [MyrtleSoftware/deepspeech#4]
Hi,
Can you please refer me to the repo/package for the warpctc that is used in the file below? 
(There are many warp-ctc related github repos out there, so not sure which one to use)
https://github.com/MyrtleSoftware/deepspeech/blob/master/src/deepspeech/loss/ctc_loss.py

**Comment by samgd** [comment]
Yes, it's this:

https://github.com/MyrtleSoftware/deepspeech/blob/995ce2d69c8da9b513a2b4e5e3f0b3bae5682373/Makefile#L15-L16

at this specific commit:

https://github.com/MyrtleSoftware/deepspeech/blob/995ce2d69c8da9b513a2b4e5e3f0b3bae5682373/Dockerfile#L57-L59

**Comment by mausamsion** [comment]
Thanks @samgd !!!
